# Generated by Django 4.2.10 on 2026-01-17 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0008_add_video_tech_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(help_text="视频内容摘要")),
                ("key_frames", models.JSONField(default=list, help_text="关键帧时间戳列表")),
                ("auto_tags", models.JSONField(default=list, help_text="AI 生成的标签")),
                ("scene_changes", models.IntegerField(default=0, help_text="场景切换次数")),
                ("dominant_colors", models.JSONField(default=list, help_text="主要颜色")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, help_text="详细摘要信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summary",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频摘要",
                "verbose_name_plural": "视频摘要",
                "db_table": "ai_video_summary",
            },
        ),
        migrations.CreateModel(
            name="ModerationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("processing", "审核中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("safe", "安全"),
                            ("unsafe", "不安全"),
                            ("uncertain", "不确定"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0, help_text="置信度 0-1")),
                ("nsfw_score", models.FloatField(default=0.0, help_text="NSFW 内容得分")),
                ("violence_score", models.FloatField(default=0.0, help_text="暴力内容得分")),
                ("sensitive_score", models.FloatField(default=0.0, help_text="敏感内容得分")),
                (
                    "flagged_frames",
                    models.JSONField(blank=True, default=list, help_text="问题帧时间戳列表"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, help_text="详细审核信息"),
                ),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_moderations",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI审核结果",
                "verbose_name_plural": "AI审核结果",
                "db_table": "ai_moderation_result",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FrameRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField(help_text="视频时间戳（秒）")),
                (
                    "detected_objects",
                    models.JSONField(default=list, help_text="识别到的物体列表"),
                ),
                (
                    "scene",
                    models.CharField(blank=True, help_text="场景分类", max_length=100),
                ),
                ("text_content", models.TextField(blank=True, help_text="OCR 识别的文字")),
                ("faces", models.JSONField(default=list, help_text="人脸信息")),
                ("confidence", models.FloatField(default=0.0, help_text="整体置信度")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, help_text="详细识别信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_recognitions",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "画面识别",
                "verbose_name_plural": "画面识别",
                "db_table": "ai_frame_recognition",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video", "timestamp"],
                        name="ai_frame_re_video_i_e8b98d_idx",
                    )
                ],
            },
        ),
    ]
