# Generated by Django 4.2.10 on 2026-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationresult",
            name="nsfw_score",
            field=models.FloatField(default=0.0, help_text="高风险得分（high）"),
        ),
        migrations.AlterField(
            model_name="moderationresult",
            name="sensitive_score",
            field=models.FloatField(default=0.0, help_text="低风险及以上得分（low+）"),
        ),
        migrations.AlterField(
            model_name="moderationresult",
            name="violence_score",
            field=models.FloatField(default=0.0, help_text="中风险及以上得分（medium+）"),
        ),
    ]
