# Generated by Django 4.2.10 on 2025-07-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_upload_video", "可以上传视频"),
                    ("can_review_video", "可以审核视频"),
                    ("can_manage_users", "可以管理用户"),
                    ("can_access_vip_content", "可以访问VIP内容"),
                ],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_vip",
            field=models.BooleanField(default=False, verbose_name="是否VIP用户"),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "普通用户"),
                    ("vip", "VIP用户"),
                    ("admin", "管理员"),
                    ("superadmin", "超级管理员"),
                ],
                default="user",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_expire_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="VIP到期时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="vip_level",
            field=models.IntegerField(
                choices=[(0, "非VIP"), (1, "青铜VIP"), (2, "白银VIP"), (3, "黄金VIP")],
                default=0,
                verbose_name="VIP等级",
            ),
        ),
        migrations.CreateModel(
            name="VIPOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(max_length=64, unique=True, verbose_name="订单号"),
                ),
                (
                    "vip_level",
                    models.IntegerField(
                        choices=[(0, "非VIP"), (1, "青铜VIP"), (2, "白银VIP"), (3, "黄金VIP")],
                        verbose_name="VIP等级",
                    ),
                ),
                ("months", models.IntegerField(default=1, verbose_name="购买月数")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="支付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=20, verbose_name="支付方式"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "VIP订单", "verbose_name_plural": "VIP订单",},
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("user", "普通用户"),
                            ("vip", "VIP用户"),
                            ("admin", "管理员"),
                            ("superadmin", "超级管理员"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="角色名称",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="权限"
                    ),
                ),
            ],
            options={"verbose_name": "用户角色", "verbose_name_plural": "用户角色",},
        ),
    ]
