# Generated by Django 4.2.10 on 2025-07-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_is_vip_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女"), ("other", "保密")],
                default="other",
                max_length=10,
                verbose_name="性别",
            ),
        ),
    ]
