# Generated by Django 4.2.10 on 2025-07-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_gender_birthday_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("email_verify", "邮箱验证"),
                            ("password_reset", "密码重置"),
                            ("email_change", "修改邮箱"),
                        ],
                        max_length=20,
                        verbose_name="验证码类型",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("is_used", models.BooleanField(default=False, verbose_name="是否已使用")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "验证码", "verbose_name_plural": "验证码",},
        ),
    ]
