# Generated by Django 4.2.10 on 2025-07-09 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_verificationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "系统通知"),
                            ("interaction", "互动消息"),
                            ("private", "私信"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                ("read", models.BooleanField(default=False, verbose_name="是否已读")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source_id",
                    models.IntegerField(blank=True, null=True, verbose_name="资源ID"),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=30, verbose_name="资源类型"),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户通知",
                "verbose_name_plural": "用户通知",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.BooleanField(default=True, verbose_name="系统通知")),
                ("interaction", models.BooleanField(default=True, verbose_name="互动通知")),
                ("private", models.BooleanField(default=True, verbose_name="私信通知")),
                ("email", models.BooleanField(default=False, verbose_name="邮件通知")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "通知设置", "verbose_name_plural": "通知设置",},
        ),
    ]
