# Generated by Django 4.2.10 on 2026-02-15 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usernotification_notificationsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMonitoringLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_percent", models.FloatField(verbose_name="CPU 使用率(%)")),
                (
                    "cpu_count",
                    models.IntegerField(blank=True, null=True, verbose_name="CPU 核心数"),
                ),
                ("memory_percent", models.FloatField(verbose_name="内存使用率(%)")),
                ("memory_used_gb", models.FloatField(verbose_name="已用内存(GB)")),
                ("memory_available_gb", models.FloatField(verbose_name="可用内存(GB)")),
                ("disk_read_mb", models.FloatField(default=0, verbose_name="磁盘读取(MB)")),
                (
                    "disk_write_mb",
                    models.FloatField(default=0, verbose_name="磁盘写入(MB)"),
                ),
                ("net_sent_mb", models.FloatField(default=0, verbose_name="网络发送(MB)")),
                ("net_recv_mb", models.FloatField(default=0, verbose_name="网络接收(MB)")),
                ("process_count", models.IntegerField(default=0, verbose_name="进程数")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="记录时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统监控日志",
                "verbose_name_plural": "系统监控日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="users_syste_created_37ee17_idx"
                    )
                ],
            },
        ),
    ]
