# Generated by Django 4.2.10 on 2026-02-15 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_systemmonitoringlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_username",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="操作者用户名"
                    ),
                ),
                (
                    "operator_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="操作 IP"
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("user_create", "创建用户"),
                            ("user_update", "更新用户"),
                            ("user_delete", "删除用户"),
                            ("admin_create", "创建管理员"),
                            ("admin_update", "更新管理员"),
                            ("admin_delete", "删除管理员"),
                            ("video_review", "视频审核"),
                            ("video_delete", "删除视频"),
                            ("comment_delete", "删除评论"),
                            ("report_handle", "处理举报"),
                            ("system_config", "系统配置"),
                            ("permission_change", "权限变更"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="日志类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("critical", "严重"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="日志级别",
                    ),
                ),
                (
                    "module",
                    models.CharField(db_index=True, max_length=100, verbose_name="模块"),
                ),
                ("action", models.CharField(max_length=200, verbose_name="操作")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=50, verbose_name="目标类型"),
                ),
                (
                    "target_id",
                    models.IntegerField(blank=True, null=True, verbose_name="目标 ID"),
                ),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=200, verbose_name="目标名称"),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, verbose_name="请求方法"),
                ),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, verbose_name="请求路径"),
                ),
                (
                    "request_params",
                    models.JSONField(blank=True, null=True, verbose_name="请求参数"),
                ),
                (
                    "response_code",
                    models.IntegerField(blank=True, null=True, verbose_name="响应代码"),
                ),
                ("response_message", models.TextField(blank=True, verbose_name="响应消息")),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="执行时长(秒)"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统操作日志",
                "verbose_name_plural": "系统操作日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="users_syste_created_420f4e_idx"
                    ),
                    models.Index(
                        fields=["operator_username", "-created_at"],
                        name="users_syste_operato_4d616e_idx",
                    ),
                    models.Index(
                        fields=["log_type", "-created_at"],
                        name="users_syste_log_typ_8ccd9b_idx",
                    ),
                    models.Index(
                        fields=["level", "-created_at"],
                        name="users_syste_level_ef1cce_idx",
                    ),
                ],
            },
        ),
    ]
