# Generated by Django 4.2.10 on 2025-07-10 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0002_videocollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="review_remark",
            field=models.TextField(blank=True, verbose_name="审核备注"),
        ),
        migrations.AddField(
            model_name="video",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="video",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "上传中"),
                    ("processing", "处理中"),
                    ("ready", "就绪"),
                    ("failed", "失败"),
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                default="uploading",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
