# Generated by Django 4.2.10 on 2025-12-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "videos",
            "0003_video_review_remark_video_reviewed_at_video_reviewer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="video",
            name="comments_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="评论数"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="duration",
            field=models.FloatField(db_index=True, default=0, verbose_name="时长(秒)"),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="是否发布"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="likes_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="点赞数"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="发布时间"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "上传中"),
                    ("processing", "处理中"),
                    ("ready", "就绪"),
                    ("failed", "失败"),
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="uploading",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(db_index=True, max_length=100, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="video",
            name="views_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="观看次数"
            ),
        ),
        migrations.AlterField(
            model_name="videoview",
            name="view_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="观看时间"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["video", "is_active", "-created_at"], name="comment_video_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user", "-created_at"], name="comment_user_idx"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["-created_at", "status", "is_published"],
                name="video_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["-views_count", "status", "is_published"], name="video_hot_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["user", "-created_at", "status"], name="video_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["category", "-created_at", "status"], name="video_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["-likes_count", "status", "is_published"],
                name="video_likes_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoview",
            index=models.Index(fields=["user", "-view_date"], name="view_user_idx"),
        ),
        migrations.AddIndex(
            model_name="videoview",
            index=models.Index(fields=["video", "-view_date"], name="view_video_idx"),
        ),
    ]
