# Generated by Django 4.2.10 on 2025-12-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_alter_comment_created_at_alter_comment_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="删除时间"
            ),
        ),
    ]
