# Generated by Django 4.2.10 on 2026-01-11 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0005_video_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Danmaku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="弹幕内容")),
                (
                    "time",
                    models.FloatField(db_index=True, default=0, verbose_name="出现时间(秒)"),
                ),
                (
                    "mode",
                    models.IntegerField(
                        choices=[(0, "滚动"), (1, "顶部"), (2, "底部")],
                        default=0,
                        verbose_name="弹幕模式",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#FFFFFF", max_length=10, verbose_name="弹幕颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danmakus",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danmakus",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "弹幕",
                "verbose_name_plural": "弹幕",
                "ordering": ["time"],
                "indexes": [
                    models.Index(
                        fields=["video", "time"], name="danmaku_video_time_idx"
                    )
                ],
            },
        ),
    ]
