# Generated by Django 4.2.10 on 2026-01-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_danmaku"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="resolution",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="最高分辨率"
            ),
        ),
    ]
