# Generated by Django 4.2.10 on 2026-01-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_add_resolution_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="aspect_ratio",
            field=models.CharField(blank=True, max_length=20, verbose_name="宽高比"),
        ),
        migrations.AddField(
            model_name="video",
            name="audio_bitrate",
            field=models.PositiveIntegerField(default=0, verbose_name="音频码率(kbps)"),
        ),
        migrations.AddField(
            model_name="video",
            name="audio_codec",
            field=models.CharField(blank=True, max_length=50, verbose_name="音频编码"),
        ),
        migrations.AddField(
            model_name="video",
            name="bitrate",
            field=models.PositiveIntegerField(default=0, verbose_name="总码率(kbps)"),
        ),
        migrations.AddField(
            model_name="video",
            name="file_size",
            field=models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
        ),
        migrations.AddField(
            model_name="video",
            name="frame_rate",
            field=models.FloatField(default=0, verbose_name="帧率"),
        ),
        migrations.AddField(
            model_name="video",
            name="height",
            field=models.PositiveIntegerField(default=0, verbose_name="视频高度"),
        ),
        migrations.AddField(
            model_name="video",
            name="video_bitrate",
            field=models.PositiveIntegerField(default=0, verbose_name="视频码率(kbps)"),
        ),
        migrations.AddField(
            model_name="video",
            name="video_codec",
            field=models.CharField(blank=True, max_length=50, verbose_name="视频编码"),
        ),
        migrations.AddField(
            model_name="video",
            name="width",
            field=models.PositiveIntegerField(default=0, verbose_name="视频宽度"),
        ),
    ]
