# Generated by Django 4.2.10 on 2026-01-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_add_subtitle_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "上传中"),
                    ("pending_subtitle_edit", "等待字幕编辑"),
                    ("processing", "处理中"),
                    ("ready", "就绪"),
                    ("failed", "失败"),
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="uploading",
                max_length=30,
                verbose_name="状态",
            ),
        ),
    ]
