# Generated by Django 4.2.10 on 2026-02-09 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0013_add_subtitle_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("illegal", "违法违规"),
                            ("vulgar", "色情低俗"),
                            ("violence", "血腥暴力"),
                            ("spam", "垃圾广告"),
                            ("copyright", "侵权"),
                            ("misleading", "虚假误导"),
                            ("harassment", "人身攻击"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="举报原因",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="详细描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已处理"),
                            ("rejected", "已驳回"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("handle_result", models.TextField(blank=True, verbose_name="处理结果")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="举报时间"
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频举报",
                "verbose_name_plural": "视频举报",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="report_status_idx"
                    ),
                    models.Index(
                        fields=["video", "-created_at"], name="report_video_idx"
                    ),
                ],
            },
        ),
    ]
